### ISSUE TITLE
PlaceModule: Why are all methods annotated with @PerActivity?

### ISSUE THREAD

**Issue by Rainer-Lang** [spirosoik/AndroidArchitecturePadawans#5]
Just asking, because I wanted to understand this scope (PerActivity) much better.
Thanks.

**Comment by spirosoik** [comment]
Hi @Rainer-Lang is the custom scope which defines that they will live as long as our Activity is alive. In other words, we can define the granularity of your scopes (@PerFragment, @PerUser, etc).

**Comment by Rainer-Lang** [comment]
So all within PlaceModule (eg Mappers and PlaceApiManager) will live as long as the Activity (here it's the PlacesFragment where PlaceApiManager is injected) lives?
But if it's a fragment like here - why not using PerFragment?

**Comment by spirosoik** [comment]
It depends in your preference @Rainer-Lang if you want to have some things based on fragments lifecycle but remember that fragment mostly follows activity's lifecycle.

**Comment by Rainer-Lang** [comment]
Ah ok. I understand. 
1) So in your example it could also be PerFragment - maybe it's not a "perfect" solution, but it's working, right?
In general:  Even if I use "something" in a fragment, normally for dagger I could use PerActivity scope.

2) If I use PerActivity/PerFragment - with which lifecycle method are objects killed? onDestroy?

Dagger is really very interesting. :)

**Comment by spirosoik** [comment]
> 1) So in your example it could also be PerFragment - maybe it's not a "perfect" solution, but it's working, right? In general: Even if I use "something" in a fragment, normally for dagger I could use PerActivity scope.

Yes exactly but it depends on your implementation and your case may you want to have on graph only `PerFragment` for some reason.

> 2) If I use PerActivity/PerFragment - with which lifecycle method are objects killed? onDestroy?

yes both of them in `onDestroy`.

**Comment by Rainer-Lang** [comment]
@spirosoik Thank you very much for your help. You clarified a lot. :)
